### ISSUE TITLE
Ready for production, if self-hosted?

### ISSUE THREAD

**Issue by LasaleFamine** [cheeaun/puppetron#1]
Hello @cheeaun, and thank you so much for building this, I was trying to do the same thing with `puppeteer`.

I saw with pleasure the it can render perfectly my Polymer application without problems, unlike `rendertron`  with whom I have some problems.

I'm wondering if `puppetron` could be production-ready if I will host my self in a production environment. What do you think? Does it need known improvements about the implementation?

**Comment by cheeaun** [comment]
Hi, thanks for the questions!

1. `Puppeteer` and in fact, headless chrome, are pretty new for now, so I'm not sure if it's really production-ready yet. So the question is not whether `Puppetron` is production-ready but more like `Puppeteer` itself. 😅
2. `Puppetron` which is hosted on [now](https://zeit.co/now), is currently open to the public, so I expect there could be a lot of abuse/traffic. I'm not making sure the site is 100% up and also not charging anything, so it'll be difficult for me to make this super stable.
3. I suggest forking this project and rewrite the code to suit your specific use-case (you probably don't need the PDF and screenshot stuff?). To prevent public abuse, you could whitelist URLs that can be passed in and host it for your internal usage. I'm currently doing that now in my current day job, basically trying to replace [Prerender](https://prerender.io/).
4. From this project, you could learn a few of the improvements I've done on how to handle weird use cases and bugs, which might not be handled on `Puppeteer`'s side.

**Comment by LasaleFamine** [comment]
Thank you for your hints. I think I will take you **3.** point as my solution. 
BTW `Puppetron` is the answer to my open `Puppeteer` issue about using it as renderer like `Rendertron`. So I really thank you for this! 👍 

I think we can close the issue then!
