### ISSUE TITLE
Demo Not working

### ISSUE THREAD

**Issue by towfiqi** [cheeaun/puppetron#10]
Hi,

Great project! just tested the demo https://puppetron.now.sh/ and its returning `Invalid URL` every time.

Thanks

**Comment by cheeaun** [comment]
Hmm, seems like this is relevant 😓  https://spectrum.chat/zeit/now/status-code-301-moved-permanently~1da6cb3d-1aff-4c62-8844-cfd11f6886f0

**Comment by quarterdeck** [comment]
Yes this is a Zeit/Now issue. They are stripping a / from the domain.

Quick fix is pull href from the url as well:

`const { href, origin, hostname, pathname, searchParams } = new URL(url);`

then check for valid url after this line rather than before but use the href:

```
if (!/^https?:\/\//i.test(href)) {
  throw new Error('Invalid URL');
}
```

**Comment by cheeaun** [comment]
Fixed in latest commits. Replacing `/[URL]` with `/?url=URL` instead.

```
https://puppetron.now.sh/screenshot?url=http://google.com
```
