### ISSUE TITLE
Docker file?

### ISSUE THREAD

**Issue by jol64** [cheeaun/puppetron#11]
Great demo site... I would like to set up a local copy using docker, but although you mention docker, I cannot see a docker build file or reference to a prefabricated image. Or am I blind?
Thanks, Joachim

**Comment by cheeaun** [comment]
Sorry, docker setup has been removed since [May](https://github.com/cheeaun/puppetron/commit/4575400f3b13c964d010929bd9ac25e09cf3a894), due to Vercel (Now) not supporting it anymore.
