### ISSUE TITLE
How CJK fonts support fixed?

### ISSUE THREAD

**Issue by suntong** [cheeaun/puppetron#7]
From https://twitter.com/cheeaun/status/902340897433501696, the before-pic has problem obviously, but I cannot seem to able to find how it is fixed in the git history. 

The tweet is on 26 Aug 2017, which commit around then fix the problem please? Thx!!

**Comment by cheeaun** [comment]
It's fixed on the (Docker) image instead. The fonts are on the OS-level, so I don't think it can be fixed from Puppeteer's side 😅 

https://github.com/cheeaun/docker-puppeteer/commit/065c0971d972ba17b5fe03f036bd0f82c811f312

☝️ It basically installs East Asian fonts.

**Comment by suntong** [comment]
Ah, gotya. THX!
